### ISSUE TITLE
more randomization

### ISSUE THREAD

**Issue by U70U** [rezamatin1290/BlumAutoBot#1]
```
# AutoPlay.py
sleep_time = random.uniform(32, 50)
            print(f"Iteration {iteration}: Wait for {sleep_time:.2f} seconds...")
            time.sleep(sleep_time)
```

if need more update i told you bro.

**Comment by rezamatin1290** [comment]
Thanks for the suggestion! I’ve added the randomization as you requested. 
If you need further changes or updates, feel free to let me know!
